services:
  maccy-nas-agent:
    build:
      context: .
    container_name: maccy-nas-agent
    restart: unless-stopped
    ports:
      - "17655:17655"
    volumes:
      - /vol1/1000/Docker/maccy/data:/data
